function convert-XMLtoCSV(){}
function loadCSV(){}
function createOrUpdateUsers(){}
function createOrUpdateGroups(){}
function deactivateNotMentionedUsers(){}
function deleteNotMentionedGroups(){}
function assosiateAccountsToGroups(){}
function createGroupDirectory(){}
function setGroupDirectoryPermissions(){}
function createUserDirectory(){}
function setUserDirectoryPermissions(){}
function renameUnusedDirectories(){}