$global:domain = "m122g.local"
$global:userOU = "GIBS/Lernende"
$global:groupOU = "GIBS/Klassengruppen"
$global:defaultPassword = "gibs.001"
$global:xmlPath = "$PSScriptRoot\..\Ressources\gibsso_AD-Export.xml"
$global:csvPath = "$PSScriptRoot\..\Ressources\gibsso_AD-Export.csv"
$global:encoding = "UTF8"